# Generated by Django 5.2.5 on 2025-08-28 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
